### PR TITLE
Added the favicon in asset folder and generate it

### PR DESCRIPTION
**Pull request by 786-aquib**
Do it as you told in your issue.

### CODE REVIEW

**Review by Mannuel25 — CHANGES_REQUESTED** [review]
Hi @786-aquib , you're expected to get more than two files upon generating the favicons.
Kindly make use of the site stated.

**Comment by 786-aquib** [comment]
the file that i have created is wrong??
because i have created a html file and other is .png file and link it...
can you please tell me what i have to do because this is my first contribution so please help me a bit

**Comment by 786-aquib** [comment]
i do some changes please check it...
And tell me if something left/wrong.

**Comment by Mannuel25** [comment]
Hello @786-aquib , what I meant was when you try generating the favicons using this [site](https://www.favicon-generator.org/), ensure you select `Generate icons for Web, Android, Microsoft, and iOS (iPhone and iPad) Apps`. A zip file will be downloaded, you can use this [site](https://www.ezyzip.com/unzip-files-online.html), to extract the files. Upon doing so, about 20+ files would be generated.

**Comment by Mannuel25** [comment]
@786-aquib still interested in working on this?
This PR will be closed if there's no update on it by tomorrow

**Comment by 786-aquib** [comment]
I will do it ..
Due to some issue i was busy...

**Comment by Mannuel25** [comment]
> I will do it .. Due to some issue i was busy...

Okay, also do well to fix all merge conflicts please.

**Comment by Mannuel25** [comment]
I'd be closing this as I got no update on it.

**Pull request closed without merging**
