### PR TITLE
Added assests/Favicons 

### PR DESCRIPTION
**Pull request by Gxgxn**

### CODE REVIEW

**Comment by Mannuel25** [comment]
Hello @Gxgxn , thanks for your interest in working on this issue, but this PR won't be merged at the moment as it's already been worked on by someone else. Thanks.

**Comment by Gxgxn** [comment]
> Hello @Gxgxn , thanks for your interest in working on this issue, but this PR won't be merged at the moment as it's already been worked on by someone else. Thanks.

Hey @Mannuel25  , I can see there is no progress on the other PR which is open. Can you give a deadline for the other PR?

**Comment by Mannuel25** [comment]
> > Hello @Gxgxn , thanks for your interest in working on this issue, but this PR won't be merged at the moment as it's already been worked on by someone else. Thanks.
> 
> Hey @Mannuel25 , I can see there is no progress on the other PR which is open. Can you give a deadline for the other PR?

Yeah, sure👍

**Comment by Mannuel25** [comment]
Hello @Gxgxn , please could you drop your LinkedIn profile url. There's a contributors page dedicated to recognize everyone who worked on the project.

**Comment by Gxgxn** [comment]
Here's my linked in profile link.
https://www.linkedin.com/in/gvgvn

**Pull request merged**
